# Use an official Node.js runtime as the base image
FROM node:18

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install application dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Build the React application (if needed)
# RUN npm run build

# Expose port (optional, only if your React app has a server component)
# EXPOSE 3000

# Specify the command to start your React application
CMD ["npm", "start"]
